import Head from "next/head";
import Image from "next/image";
import MenuBar from "../Components/MenuBar";
import Navbar from "../Components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing Page | Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        heading="Capture Photography"
        message="I capture moments in nature and keep them alive"
      />
    </div>
  );
}
