import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing Page | Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,200;0,300;0,400;0,600;0,700;1,200;1,400 & display=swap"
          rel="stylesheet"
        /> */}
      </Head>
    </div>
  );
}
